<?php

namespace App\Services;

use App\Models\User;

class PlayerService extends BaseService
{
    protected const MODEL = User::class;

    public function getById(int $id)
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }
}
