version: '3.8'
services:
  database:
    container_name: mafia_database
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
    volumes:
      - './docker/mysql-data/db:/var/lib/mysql'
    ports:
      - '${DB_PORT}:${DB_PORT}'
  php:
    container_name: mafia_php
    build:
      context: ./docker/php/
    ports:
      - '9006:9000'
    volumes:
      - .:/var/www/backend
    depends_on:
      - database
  nginx:
    container_name: mafia_nginx
    build:
      context: ./docker/nginx/
    ports:
      - '8086:80'
    volumes:
      - .:/var/www/backend
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
